### ISSUE TITLE
能实现添加主屏么？

### ISSUE THREAD

**Issue by danielmlc** [pyyzcwg2833/gg-music#1]

**Comment by ApsarasX** [comment]
可以的，但是需要浏览器支持PWA

**Comment by danielmlc** [comment]
一直在chrome上测试，没有出现添加主屏，是现在还没实现吗

**Comment by ApsarasX** [comment]
![img_20180306_085703](https://user-images.githubusercontent.com/24390069/37008337-8ab67112-211c-11e8-8c14-022befa5ab79.png)
看划线的地方，点击“添加到主屏幕”

**Comment by danielmlc** [comment]
需要弹出添加提醒才行
