### ISSUE TITLE
文件入口在哪？

### ISSUE THREAD

**Issue by webgirl1995** [pyyzcwg2833/gg-music#3]
my-header组件怎么加进去的，在app.vue中没发现，可以详细讲一下吗？

**Comment by ApsarasX** [comment]
my-header在src/pages/main/main.vue里，Main这个组件挂载到app.vue的<router-view></router-view>里

**Comment by webgirl1995** [comment]
嗯嗯，看见了，谢谢，项目很棒，很值得学习!
